server:
  contextPath: /${backend.app.name}
  port: ${backend.app.port}

spring-boot-application: ${backend.app.name}

security:
  oauth2:
    client:
      client-id: admin
      client-secret: admin
      scope: read,write
      auto-approve-scopes: '.*'
   
logging:
  level:
    org.springframework.security: DEBUG

spring:
  resources:
    chain:
      enabled: true
